spring.application.name=TPBackInkaMetrics
spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
logging.level.org.springframework.security=DEBUG
#esta linea
spring.config.import=optional:file:./src/main/resources/application-local.properties
jwt.secret=${JWT_SECRET}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.port=${PORT:8080}


spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# RapidAPI
rapidapi.key=${RAPIDAPI_KEY}
rapidapi.twitch.host=twitch-scraper2.p.rapidapi.com
rapidapi.youtube.host=youtube-v311.p.rapidapi.com
rapidapi.kick.host=kick-com-api.p.rapidapi.com

