spring.application.name=InkaMetrics
spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost/InkaMetrics
spring.datasource.username=postgres
spring.datasource.password=postgres
server.port=8080
